#!/usr/bin/env zsh

# `o` with no arguments opens the current directory, otherwise opens the given
# location
function finder() {
	if [ $# -eq 0 ]; then
		open .;
	else
		open "$@";
	fi;
}

alias o="finder"