#!/usr/bin/env zsh

# @description Determine size of a file or total size of a directory
# @arg $1 string The file or directory
function fs() {
	if du -b /dev/null > /dev/null 2>&1; then
		local arg=-sbh;
	else
		local arg=-sh;
	fi
	# shellcheck disable=SC2199
	if [[ -n $@ ]]; then
    du $arg -- "$@"
  else
    du $arg .[^.]* ./*
  fi;
}